stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
    - config/config.yaml
    - data/raw
    - src/data_ingestion.py
    outs:
    - data/interim/case_study1.csv
    - data/interim/case_study2.csv
  data_transformation:
    cmd: python -m src.data_transformation
    deps:
    - config/config.yaml
    - data/interim/case_study1.csv
    - data/interim/case_study2.csv
    - src/data_transformation.py
    outs:
    - data/processed/merged_data.csv
  feature_engineering:
    cmd: python -m src.feature_engineering
    deps:
    - config/config.yaml
    - data/processed/merged_data.csv
    - src/feature_engineering.py
    outs:
    - data/processed/encoded_data.csv
  feature_selection:
    cmd: python -m src.feature_selection
    deps:
    - config/config.yaml
    - data/processed/encoded_data.csv
    - src/feature_selection.py
    params:
    - feature_selection.p_value_threshold
    - feature_selection.vif_threshold
    outs:
    - data/processed/selected_data.csv
  feature_refinement:
    cmd: python -m src.feature_refinement
    deps:
    - config/config.yaml
    - data/processed/selected_data.csv
    - src/feature_refinement.py
    params:
    - feature_refinement.correlation_threshold
    - feature_refinement.importance_threshold
    outs:
    - data/processed/final_data.csv
  model_trainer:
    cmd: python -m src.model_trainer
    deps:
    - config/config.yaml
    - data/processed/final_data.csv
    - src/model_evaluation.py
    - src/model_trainer.py
    params:
    - model.random_state
    - model.test_size
    - smote.p0_multiplier
    - smote.p1_multiplier
    - smote.p2_multiplier
    - smote.p3_multiplier
    - xgboost.eval_metric
    - xgboost.learning_rate
    - xgboost.max_depth
    - xgboost.n_estimators
    outs:
    - artifacts/model/model.pkl
    - reports/metrics.json
    - reports/model_info.json
